name:  test cases


on:
  push:
    branches: 
      - "main"
jobs:
    build_and_test: 
        runs-on: ubuntu-latest


        strategy:
          matrix:
            node-version: [ 16.x]


        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install 
              run: npm  ci # use ci for clean install 
            - name: Test
              run: npm run test